# Generated by Django 4.0.4 on 2022-05-31 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Phone_No', models.CharField(max_length=30, unique=True)),
                ('Credot_Card_No', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departure_Time', models.DateTimeField(null=True)),
                ('Landing_Time', models.DateTimeField(null=True)),
                ('Airline_Company_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.airline_companies')),
                ('Destination_Country_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destination_Country_Id', to='AirlineApp.countries')),
                ('Origin_Country_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Origin_Country_Id', to='AirlineApp.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('User_Role', models.CharField(choices=[('User', 'User'), ('Flight_Company', 'Flight Company'), ('Administrator', 'Administrator')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.customers')),
                ('Flight_Id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.flights')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='User_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.users'),
        ),
        migrations.AddField(
            model_name='airline_companies',
            name='Country_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.countries'),
        ),
        migrations.AddField(
            model_name='airline_companies',
            name='User_Id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.users'),
        ),
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('User_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.users')),
            ],
        ),
    ]
