# Generated by Django 4.0.4 on 2022-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_Role',
            field=models.CharField(choices=[('User', 'User'), ('Flight_Company', 'Flight Company'), ('Administrator', 'Administrator')], max_length=30),
        ),
    ]
