# Generated by Django 4.0.4 on 2022-06-21 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineApp', '0003_flights_remaining_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Departure_Time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Landing_Time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
