# Generated by Django 4.0.4 on 2022-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineApp', '0004_alter_flights_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
