# Generated by Django 4.0.4 on 2022-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineApp', '0007_alter_administrators_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='image',
            field=models.ImageField(default='tamplates/images/image.jpg', upload_to='templates/images/'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Remaining_Tickets',
            field=models.IntegerField(default=0),
        ),
    ]
