# Generated by Django 4.0.4 on 2022-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineApp', '0008_countries_image_alter_flights_remaining_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='image',
            field=models.ImageField(default='images/image.jpg', upload_to='images/'),
        ),
    ]
